  CREATE TABLE am_app_backups 
   (	"ID" NUMBER, 
	"REVISION" NUMBER, 
	"BACKUP_TYPE" VARCHAR2(30 BYTE), 
	"BACKUP_STATUS" VARCHAR2(30 BYTE), 
	"APPLICATION_ID" NUMBER NOT NULL ENABLE, 
	"APPLICATION_NAME" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"MANIFEST" CLOB, 
	"BLOB_ID" NUMBER, 
	"BLOB_CONTENT" BLOB, 
	"LOCKED_ON" DATE, 
	"LOCKED_BY" VARCHAR2(255 BYTE), 
	"LAST_UPDATED_BY" VARCHAR2(255 BYTE), 
	"LAST_UPDATED_ON" DATE
   )