CREATE TABLE AM_APP_BACKUPS_DUMM 
   (	ID NUMBER, 
	SECURITY_GROUP_ID NUMBER NOT NULL ENABLE, 
	REVISION NUMBER, 
	BACKUP_TYPE VARCHAR2(30 BYTE), 
	BACKUP_STATUS VARCHAR2(30 BYTE), 
	APPLICATION_ID NUMBER NOT NULL ENABLE, 
	APPLICATION_NAME VARCHAR2(255 BYTE), 
	DESCRIPTION VARCHAR2(4000 BYTE), 
	MANIFEST CLOB, 
	OBJECT_ID NUMBER, 
	LOCKED_BY VARCHAR2(255 BYTE), 
	LOCKED_ON DATE, 
	CREATED_BY VARCHAR2(255 BYTE), 
	CREATED_ON DATE, 
	LAST_UPDATED_BY VARCHAR2(255 BYTE), 
	LAST_UPDATED_ON DATE, 
	BLOB_CONTENT BLOB, 
	FILENAME VARCHAR2(400 BYTE), 
	MIME_TYPE VARCHAR2(255 BYTE)
   );


