CREATE TABLE AM_DEVELOPER_AUDIT_LOG_DUM 
   (	APPLICATION_ID NUMBER, 
	DEVELOPER VARCHAR2(255 BYTE), 
	AUDIT_DATE DATE, 
	UPDATED DATE, 
	AUDIT_ACTION VARCHAR2(1 BYTE), 
	PAGE_ID NUMBER, 
	PAGE_NAME VARCHAR2(255 BYTE), 
	COMPONENT VARCHAR2(30 BYTE), 
	COMPONENT_NAME VARCHAR2(4000 BYTE), 
	OBJECT_NAME VARCHAR2(4000 BYTE), 
	SECURITY_GROUP_ID NUMBER NOT NULL ENABLE, 
	FLOW_TABLE_PK NUMBER
   );
