--DROP TABLE AM_TEMPLATE_OPT_GROUP;

CREATE GLOBAL TEMPORARY TABLE AM_TEMPLATE_OPT_GROUP 
(	EXPORT_ID NUMBER NOT NULL, 
	THEME_ID NUMBER NOT NULL, 
	DISPLAY_NAME VARCHAR2(30 CHAR) NOT NULL, 
	TEMPLATE_OPT_GROUP_APEX_ID NUMBER NOT NULL
   )   ON COMMIT DELETE ROWS ;

CREATE UNIQUE INDEX AM_TEMPLATE_OPT_GROUP_UI1 ON AM_TEMPLATE_OPT_GROUP(EXPORT_ID, TEMPLATE_OPT_GROUP_APEX_ID) ;
